### ISSUE TITLE
Correcion del checkstyle de edu/uclm/esi/iso2/banco20193capas/model/TarjetaDebito.java

### ISSUE THREAD

**Issue by Martineez99** [Gerole10/JuicyCodexTestingMant#13]
Arreglar los errores de checkstyle de esta clase.

**Comment by JoseOteroAguado** [comment]
![errores](https://user-images.githubusercontent.com/56037375/71519927-dbce1b80-28b9-11ea-8b68-8bd6ff87f940.jpeg)

**Comment by JoseOteroAguado** [comment]
![1 2](https://user-images.githubusercontent.com/56037375/71522497-36b94000-28c5-11ea-9443-9e3bd39e4396.jpeg)
