### ISSUE TITLE
Corrección edu/uclm/esi/iso2/banco20193capas/model/TarjetaDebito.java

### ISSUE THREAD

**Issue by Martineez99** [Gerole10/JuicyCodexTestingMant#6]
Corrección de los errores que se muestran en el informe PMD sobre la clase TarjetaDebito.

**Comment by JoseOteroAguado** [comment]
![debito](https://user-images.githubusercontent.com/56037375/71520029-6dd62400-28ba-11ea-9a75-b08eb19e7c0b.jpeg)

**Comment by Martineez99** [comment]
![TARJETADEBITO](https://user-images.githubusercontent.com/56037382/71521489-4d5d9800-28c1-11ea-9d44-34b8fdf7b755.PNG)
Tras corregir fallos
