### ISSUE TITLE
Corrección edu/uclm/esi/iso2/banco20193capas/model/TarjetaCredito.java

### ISSUE THREAD

**Issue by Martineez99** [Gerole10/JuicyCodexTestingMant#7]
Corrección de los errores que se muestran en el informe PMD sobre la clase TarjetaCredito.

**Comment by JoseOteroAguado** [comment]
![credito](https://user-images.githubusercontent.com/56037375/71520013-5303af80-28ba-11ea-93e1-76864c89ecd6.jpeg)

**Comment by Martineez99** [comment]
![TARJETACREDITO](https://user-images.githubusercontent.com/56037382/71521515-71b97480-28c1-11ea-85e2-ca7f5d671eda.PNG)
Tras corregir errores.
